apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::481173330898:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-139H5XQVQW3F3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::481173330898:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-19T08:40:18Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2020-12-19T08:40:18Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2020-12-19T13:35:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "51103"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dfbd27f0-203c-462f-9a17-2e6cd29d05f4
